
# dataset info
dataset_name: "DUTS" 
dataset_path: "/mnt/data1/ImageSOD/DUTS/"

# image info
channels: 3
im_width: 256
im_height: 256

# training params
batch_size: 4
num_epochs: 100
val_interval: 2000 # steps
ckpt_interval: 5  # epochs


 
