
# dataset info
dataset_name: "UFO-120" 
dataset_path: "/mnt/data1/ImageSR/UFO-120/"

# image info
channels: 3
im_width: 256
im_height: 256

# training params
batch_size: 4
num_epochs: 50
val_interval: 1000 # steps
ckpt_interval: 5  # epochs


 
